audio_dir: /hdd/hdd1/lyj/UrbanSound8K/audio
batch_size: 10
epochs: 100
epoch_val: 1

input_size: 513
hidden_size: 600
num_layer: 3
window_length: 1024
n_hop: 512
source_random: False
gpu: '1'
lr: 1.0e-4